spring:
  application:
    name: kenny-ai
  ai:
    vectorstore:
      redis:
        initialize-schema: true
        index-name: spring_ai_index
        prefix: "doc:"
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gpt-oss:20b
      embedding:
        options:
          model: bge-m3:567m
    openai:
      base-url: https://openrouter.ai/api
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen/qwen3-14b:free
  data:
    redis:
      host: localhost
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/KennyAi?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.kenny.kenny_ai: debug
